### Importing Libraries

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics._regression import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [2]:
os.listdir( '../data/preprocessed data' )

['pre-processed_data.csv']

In [3]:
df = pd.read_csv( '../data/preprocessed data/pre-processed_data.csv' )

In [4]:
df.sample()

,study_hours,class_attendance,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,course_diff,gender_female,gender_male,...,course_Bachelor of Science,course_Bachelor of Technology,course_Diploma,internet_access_no,internet_access_yes,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
5158,5.2,72.5,7.8,1,2,1,83.0,5,0,1,...,1,0,0,0,1,1,0,0,0,0


## Split features into X & y

In [5]:
X = df.drop( columns = 'exam_score' )
y = df['exam_score']

In [6]:
X.shape

(20000, 24)

## Split into training & testing

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

# Model Selection

### Ensemble models

In [8]:
knn_model = KNeighborsRegressor( n_neighbors= 1 )

In [9]:
X_train.shape

(16000, 24)

In [10]:
X_test.shape

(4000, 24)

In [11]:
y_test

10650     31.1
2041      81.6
8668      68.0
1114     100.0
13902     84.8
         ...  
4073      58.6
7442      53.3
9999      58.8
1870      45.3
15196     42.7
Name: exam_score, Length: 4000, dtype: float64

In [12]:
knn_model.fit( X_train, y_train )

KNeighborsRegressor(n_neighbors=1)

In [13]:
y_pred_train = knn_model.predict( X_train )
y_pred_train[:5]

array([87.6, 80.4, 94.5, 50.7, 79.8])

In [14]:
y_test[100:106]

15304    79.0
4309     47.5
4484     58.3
11013    75.1
4770     47.6
2712     49.2
Name: exam_score, dtype: float64

In [15]:
18 / 3

6.0

In [16]:
y_pred_test = knn_model.predict( X_test )

In [17]:
y_pred_test[100:106]

array([79.5, 32.2, 52. , 70.2, 56.3, 42.3])

In [18]:
pd.DataFrame({
    'Actual' : y_test[100:106],
    'Predicted' : y_pred_test[100:106],
    'Residuals' : y_test[100:106] - y_pred_test[100:106]
})

,Actual,Predicted,Residuals
15304,79.0,79.5,-0.5
4309,47.5,32.2,15.3
4484,58.3,52.0,6.3
11013,75.1,70.2,4.9
4770,47.6,56.3,-8.7
2712,49.2,42.3,6.9


In [19]:
0.5 + 15.3 + 6.3 + 4.9 

27.0

## metrics

### MAE ( Mean Absolute Error ) ->  Look on the Avg. Error
### MSE ( Mean Squared Error )  ->  Triggers if there is high residuals (differences)
### RMSE ( Root Mean Squared Error ) -> Error between MAE & MSE

In [20]:
MAE_train = mean_absolute_error( y_train, y_pred_train )
MAE_test = mean_absolute_error( y_test, y_pred_test )

MSE_train = mean_squared_error( y_train, y_pred_train )
MSE_test = mean_squared_error( y_test, y_pred_test )

RMSE_train = root_mean_squared_error( y_train, y_pred_train )
RMSE_test = root_mean_squared_error( y_test, y_pred_test )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )
print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )


Mean Absolute Error of training : 0.0
Mean Absolute Error of Testing : 12.216742750000002

Mean Squared Error of training : 0.0
Mean Squared Error of Testing : 234.81223721774998

Root Mean Squared Error of Training : 0.0
Root Mean Squared Error of Testing : 15.323584346286282


### Evaluation of previous n_neighbors = 5
**9.4, 136, 11.6**

### Calc. Cross Validation Score

In [21]:
cross_val_score( knn_model, X_train, y_train, cv= 4, scoring='neg_mean_squared_error').mean()

np.float64(-232.82450976693747)

In [22]:
pd.set_option( 'display.max_columns', None)

In [23]:
X_train.sample()

,study_hours,class_attendance,sleep_hours,sleep_quality,facility_rating,exam_difficulty,course_diff,gender_female,gender_male,gender_other,course_Bachelor of Arts,course_Bachelor of Business Administration,course_Bachelor of Commerce,course_Bachelor of Computer Applications,course_Bachelor of Science,course_Bachelor of Technology,course_Diploma,internet_access_no,internet_access_yes,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
6344,4.44,76.5,6.1,0,0,0,2,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0


In [24]:
234.81223721774998 ** 0.5

15.323584346286282

## Curse of Dimensiality

## Fine Tuning

# Testing

In [25]:
df.sample()

,study_hours,class_attendance,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,course_diff,gender_female,gender_male,gender_other,course_Bachelor of Arts,course_Bachelor of Business Administration,course_Bachelor of Commerce,course_Bachelor of Computer Applications,course_Bachelor of Science,course_Bachelor of Technology,course_Diploma,internet_access_no,internet_access_yes,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
5868,3.52,93.5,5.2,2,2,0,91.3,3,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1


## Testing GridSearchCV on KNN Model

In [26]:
knn_model = KNeighborsRegressor(  )

In [27]:
gs_knn =  GridSearchCV(
    estimator= knn_model,
    param_grid= { 'n_neighbors' : [ 2, 3, 4, 5, 6, 7 ] }
)

In [28]:
gs_knn.fit( X_train, y_train )

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7]})

In [29]:
gs_knn.best_params_

{'n_neighbors': 7}

In [30]:
y_test

10650     31.1
2041      81.6
8668      68.0
1114     100.0
13902     84.8
         ...  
4073      58.6
7442      53.3
9999      58.8
1870      45.3
15196     42.7
Name: exam_score, Length: 4000, dtype: float64

In [31]:
y_pred_test

array([45.7, 51.5, 67.4, ..., 57.4, 63.9, 63.2], shape=(4000,))

In [32]:
knn_comparison_df = pd.DataFrame({
    'Actual (True)' : y_test,
    'Predicted (KNN)' : y_pred_test,
    'Residuals' : np.abs( y_test- y_pred_test )
})
knn_comparison_df

,Actual (True),Predicted (KNN),Residuals
10650,31.1,45.7,14.6
2041,81.6,51.5,30.1
8668,68.0,67.4,0.6
1114,100.0,100.0,0.0
13902,84.8,92.8,8.0
...,...,...,...
4073,58.6,60.6,2.0
7442,53.3,48.4,4.9
9999,58.8,57.4,1.4
1870,45.3,63.9,18.6


In [33]:
knn_comparison_df

,Actual (True),Predicted (KNN),Residuals
10650,31.1,45.7,14.6
2041,81.6,51.5,30.1
8668,68.0,67.4,0.6
1114,100.0,100.0,0.0
13902,84.8,92.8,8.0
...,...,...,...
4073,58.6,60.6,2.0
7442,53.3,48.4,4.9
9999,58.8,57.4,1.4
1870,45.3,63.9,18.6


## Visualize Residuals

In [34]:
px.line( knn_comparison_df.head( 25 ), x  = ['Actual (True)', 'Predicted (KNN)'] )

In [35]:
knn_comparison_df.head( 25 )

,Actual (True),Predicted (KNN),Residuals
10650,31.1,45.700,14.600
2041,81.6,51.500,30.100
8668,68.0,67.400,0.600
1114,100.0,100.000,0.000
13902,84.8,92.800,8.000
11963,52.8,43.900,8.900
11072,53.1,50.200,2.900
3002,81.0,98.800,17.800
19771,72.6,50.400,22.200
8115,25.4,19.599,5.801


In [36]:
px.histogram( knn_comparison_df, x  = ['Actual (True)', 'Predicted (KNN)'] )

<hr>

# [2] Linear Regression

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
lin_reg_model = LinearRegression()

In [39]:
os.cpu_count()

4

In [40]:
lin_reg_model.fit( X_train, y_train )

LinearRegression()

In [41]:
y_pred_train_lr = lin_reg_model.predict( X_train )
y_pred_test_lr = lin_reg_model.predict( X_test )

In [42]:
y_pred_train_lr

array([77.08540499, 83.54623209, 80.63310689, ..., 57.29706372,
       40.55708554, 51.19058777], shape=(16000,))

In [43]:
y_train

5894     87.6
3728     80.4
8958     94.5
7671     50.7
5999     79.8
         ... 
11284    75.4
11964    83.8
5390     59.5
860      44.0
15795    49.7
Name: exam_score, Length: 16000, dtype: float64

# Intercept -> b

In [44]:
lin_reg_model.intercept_

np.float64(-3.8845610110956343)

In [45]:
X_train.shape

(16000, 24)

In [46]:
lin_reg_model.coef_

array([ 5.87984532e+00,  3.44686431e-01,  1.43688262e+00,  4.66803584e+00,
        3.90089950e+00,  7.57607919e-02, -5.27043041e-03, -8.23191561e-02,
       -3.45641438e-02,  1.16883300e-01,  5.06988542e-02, -3.55331817e-02,
       -3.71061723e-02,  8.79725266e-02, -2.28248471e-01,  1.52365809e-01,
        9.85063512e-03, -3.91517725e-02,  3.91517725e-02,  6.22185033e+00,
       -1.55578786e+00,  1.24665746e+00, -2.64984969e+00, -3.26287025e+00])

### Optimization Algorithm

In [47]:
X_train.columns

Index(['study_hours', 'class_attendance', 'sleep_hours', 'sleep_quality',
       'facility_rating', 'exam_difficulty', 'course_diff', 'gender_female',
       'gender_male', 'gender_other', 'course_Bachelor of Arts',
       'course_Bachelor of Business Administration',
       'course_Bachelor of Commerce',
       'course_Bachelor of Computer Applications',
       'course_Bachelor of Science', 'course_Bachelor of Technology',
       'course_Diploma', 'internet_access_no', 'internet_access_yes',
       'study_method_coaching', 'study_method_group study',
       'study_method_mixed', 'study_method_online videos',
       'study_method_self-study'],
      dtype='object')

## Y = b + p1x1 + p2x2 + p3x3 + p4x4 +  .......... p24x24

In [48]:
print( 'Linear Regression Evaluation :' )
print( '-------------------------' )
print(  )

MAE_train = mean_absolute_error( y_train, y_pred_train_lr )
MAE_test = mean_absolute_error( y_test, y_pred_test_lr )

MSE_train = mean_squared_error( y_train, y_pred_train_lr )
MSE_test = mean_squared_error( y_test, y_pred_test_lr )

RMSE_train = root_mean_squared_error( y_train, y_pred_train_lr )
RMSE_test = root_mean_squared_error( y_test, y_pred_test_lr )

print( f'Mean Absolute Error of training : { MAE_train }' )
print( f'Mean Absolute Error of Testing : { MAE_test }' )

print(  )
print( f'Mean Squared Error of training : { MSE_train }' )
print( f'Mean Squared Error of Testing : { MSE_test }' )
print(  )
print( f'Root Mean Squared Error of Training : { RMSE_train }' )
print( f'Root Mean Squared Error of Testing : { RMSE_test }' )

Linear Regression Evaluation :
-------------------------

Mean Absolute Error of training : 7.849729059806823
Mean Absolute Error of Testing : 7.86201359973347

Mean Squared Error of training : 95.82557389270734
Mean Squared Error of Testing : 95.46814634090096

Root Mean Squared Error of Training : 9.789053779232564
Root Mean Squared Error of Testing : 9.770780231941611


### Model Serialization ( Saving ) ( Dumping )
#### Save to extension .pkl

In [49]:
import joblib
import pickle

In [50]:
lin_reg_model

LinearRegression()

In [51]:
os.listdir( '../artifacts' )

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../artifacts'

In [ ]:
# joblib.dump( lin_reg_model, '../artifacts/exam_score_model.pkl' )

In [ ]:
df.sample()

,study_hours,class_attendance,sleep_hours,sleep_quality,facility_rating,exam_difficulty,exam_score,course_diff,gender_female,gender_male,gender_other,course_Bachelor of Arts,course_Bachelor of Business Administration,course_Bachelor of Commerce,course_Bachelor of Computer Applications,course_Bachelor of Science,course_Bachelor of Technology,course_Diploma,internet_access_no,internet_access_yes,study_method_coaching,study_method_group study,study_method_mixed,study_method_online videos,study_method_self-study
2799,4.07,99.4,7.4,0,0,0,64.5,6,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0


In [ ]:
df.shape

(20000, 25)

### Define a function to evaluate any regressor

In [ ]:
#### model

<h3>Import a colorama library for styling the color of words and paragraphs

<h4> Fore Stands to foreground color

In [ ]:
from colorama import Fore

In [ ]:
print(  Fore.GREEN + 'hello' )

hello


In [ ]:
def evaluate_regressor( model, model_name: str ,X_train, X_test, y_train, y_test  ) :
    
    print( 'Training.........' + '\n' )
    
    print( model_name + ':' )
    print( '-'*20 )
    
    model.fit( X_train, y_train ) # Training !
    y_pred_train = model.predict( X_train )
    y_pred_test = model.predict( X_test )

    print(  )

    MAE_train = mean_absolute_error( y_train, y_pred_train )
    MSE_train = mean_squared_error( y_train, y_pred_train )
    
    RMSE_train = root_mean_squared_error( y_train, y_pred_train )
    
    MAE_test = mean_absolute_error( y_test, y_pred_test )
    MSE_test = mean_squared_error( y_test, y_pred_test )
    RMSE_test = root_mean_squared_error( y_test, y_pred_test )

    print( f'Mean Absolute Error of training : { MAE_train }' )
    print( Fore.WHITE + f'Mean Absolute Error of Testing : { MAE_test }' )
    print(  )

    print( Fore.CYAN + f'Mean Squared Error of training : { MSE_train }' )
    print( Fore.RED  + f'Mean Squared Error of Testing : { MSE_test }' )
    print(  )

    print( Fore.WHITE + f'Root Mean Squared Error of Training : { RMSE_train }' )
    print( Fore.WHITE + f'Root Mean Squared Error of Testing : { RMSE_test }' )


## [1] KNN

In [ ]:
knn_model = KNeighborsRegressor( n_neighbors=7 )

In [ ]:
evaluate_regressor( knn_model, 'K Neighbors Regressor', X_train, X_test, y_train, y_test )

Training.........

K Neighbors Regressor:
--------------------

Mean Absolute Error of training : 7.819387026785714
Mean Absolute Error of Testing : 9.272969892857141

Mean Squared Error of training : 94.85337002898342
Mean Squared Error of Testing : 131.7767803332194

Root Mean Squared Error of Training : 9.73926948127956
Root Mean Squared Error of Testing : 11.47940679361174


## [2] Linear Regression 

In [ ]:
lin_reg_model = LinearRegression()

In [ ]:
evaluate_regressor( lin_reg_model, 'Linear Regression without regularization', X_train, X_test, y_train, y_test  )

Training.........

Linear Regression without regularization:
--------------------

Mean Absolute Error of training : 7.849729059806823
Mean Absolute Error of Testing : 7.86201359973347

Mean Squared Error of training : 95.82557389270734
Mean Squared Error of Testing : 95.46814634090096

Root Mean Squared Error of Training : 9.789053779232564
Root Mean Squared Error of Testing : 9.770780231941611


## [3] Linear Regression with regularization L1 ( Lasso )

In [ ]:
lin_reg_L1 = Lasso( alpha = 0.2 )

In [ ]:
evaluate_regressor( lin_reg_L1, 'Linear Regression with REGULARIZATION ( L1 )', X_train, X_test, y_train, y_test )

Training.........

Linear Regression with REGULARIZATION ( L1 ):
--------------------

Mean Absolute Error of training : 7.896820765859728
Mean Absolute Error of Testing : 7.918284948378739

Mean Squared Error of training : 96.78491626380304
Mean Squared Error of Testing : 96.60217510369358

Root Mean Squared Error of Training : 9.837932519782957
Root Mean Squared Error of Testing : 9.82864055216659


## [4] Linear Regression with regularization L2 ( Ridge )

In [ ]:
ridge = Ridge(  )

In [ ]:
ridge.fit(X_train, y_train)

Ridge()

In [ ]:
ridge.coef_

array([ 5.87977708e+00,  3.44686359e-01,  1.43684917e+00,  4.66759262e+00,
        3.90052869e+00,  7.57601264e-02, -5.27518173e-03, -8.22743750e-02,
       -3.45789057e-02,  1.16853281e-01,  5.06371020e-02, -3.54987234e-02,
       -3.70716986e-02,  8.79547117e-02, -2.28162548e-01,  1.52286863e-01,
        9.85429350e-03, -3.91308065e-02,  3.91308065e-02,  6.21991962e+00,
       -1.55526832e+00,  1.24626532e+00, -2.64902408e+00, -3.26189254e+00])

In [ ]:
evaluate_regressor( ridge, 'Linear Regression with REGULARIZATION ( L2 )', X_train, X_test, y_train, y_test)

Training.........

Linear Regression with REGULARIZATION ( L2 ):
--------------------

Mean Absolute Error of training : 7.849739744732457
Mean Absolute Error of Testing : 7.862034248342009

Mean Squared Error of training : 95.82557531103602
Mean Squared Error of Testing : 95.46824428283712

Root Mean Squared Error of Training : 9.78905385167719
Root Mean Squared Error of Testing : 9.770785243921653


## [5] Support Vector Machine

In [ ]:
from sklearn.svm import SVR

In [ ]:
svm_regressor = SVR(  )

In [ ]:
evaluate_regressor( svm_regressor, 'SVM', X_train, X_test, y_train, y_test  )

Training.........

SVM:
--------------------



Mean Absolute Error of training : 9.628362006255745
Mean Absolute Error of Testing : 9.809015763770596

Mean Squared Error of training : 142.56961963495664
Mean Squared Error of Testing : 145.43736840460895

Root Mean Squared Error of Training : 11.940252075854874
Root Mean Squared Error of Testing : 12.059741639214703


## [6] Support Vector Machine with Scaling

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [ ]:
svm_pipeline = make_pipeline(StandardScaler(), SVR())

In [ ]:
svm_pipeline

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [ ]:
import joblib
import pickle

In [ ]:
joblib.dump(svm_pipeline, '../app/artifacts/svm_pipeline.pkl')

['../artifacts/svm_pipeline.pkl']

In [ ]:
evaluate_regressor( svm_pipeline, 'SVM With Scaling', X_train, X_test, y_train, y_test)

Training.........

SVM With Scaling:
--------------------

Mean Absolute Error of training : 7.764041233140608
Mean Absolute Error of Testing : 8.026937148939252

Mean Squared Error of training : 95.38082144931604
Mean Squared Error of Testing : 98.9454700445467

Root Mean Squared Error of Training : 9.76631053414318
Root Mean Squared Error of Testing : 9.947133760262133


### Try Fine-Tuning

<h3> if kernel == 'poly' --> higher degree --> pruning overfitting 

<h3>if gamma small -->Try not to fit all data --> high error --> underfitting
<h3> if gamma high --> FIT all the data as possible --> low error --> Overfitting

In [ ]:
#### C ---> Regularization Parameter 
#### High C ---> Model tries hard to fit all data --> risk overfitting
### Low C --> Model allows errors --> risk underfitting 

In [ ]:
test= pd.Series([1,2,3,4,20])

In [ ]:
test

0     1
1     2
2     3
3     4
4    20
dtype: int64

<hr>

In [ ]:
test.describe()

count     5.000000
mean      6.000000
std       7.905694
min       1.000000
25%       2.000000
50%       3.000000
75%       4.000000
max      20.000000
dtype: float64

In [ ]:
mean=test.describe()['mean']
s=test.describe()['std']
mean,s

(np.float64(6.0), np.float64(7.905694150420948))

In [ ]:
test_after_scaling=(test-mean)/s
test_after_scaling

0   -0.632456
1   -0.505964
2   -0.379473
3   -0.252982
4    1.770875
dtype: float64

In [ ]:
test_after_scaling.describe()

count    5.000000
mean     0.000000
std      1.000000
min     -0.632456
25%     -0.505964
50%     -0.379473
75%     -0.252982
max      1.770875
dtype: float64

<h3>Range of Values After Scaling

In [ ]:
1.770875--0.632456

2.403331

In [ ]:
svm_model=SVR(gamma=0.2, C=0.5)

In [ ]:
gs_svm=GridSearchCV(
    svm_regressor,
    param_grid={
    'gamma':[0.2,0.4,0.5,0.7],
    'C':[0.2,0.4,0.5,0.7]
    })


<h3> Train X and Y for all combinations
<h4> Takes much time around 10-15 mins

In [ ]:
gs_svm.fit(X_train,y_train)

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.2, 0.4, 0.5, 0.7],
                         'gamma': [0.2, 0.4, 0.5, 0.7]})

In [ ]:
gs_svm.best_params_

{'C': 0.7, 'gamma': 0.2}